name: Java SDK Build & Release JDK21

on:
  workflow_dispatch:

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
jobs:
  validation:
    name: "gradle-wrapper-validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  tagging:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      version: ${{ steps.tag.outputs.version }}
      prerelease: ${{ steps.tag.outputs.prerelease }}
    steps:
      - name: Fetch head tag from kp-protocols-clientsdk
        id: tag
        run: |
          git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
          cd proto-repo
          head_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
          if [[ -z "${head_tag}" ]]; then
            echo "No tag found on the head commit of kp-protocols-clientsdk repo. Failing the action."
            exit 1
          else
            echo "tag=${head_tag}" >> $GITHUB_OUTPUT
            echo "version=${head_tag#v}" >> $GITHUB_OUTPUT
            if [[ "${head_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
          fi

  publish:
    needs:
      - validation
      - tagging
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout proto repository
        run: |
          git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
          mv proto-repo/src .
          rm -r proto-repo
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Setup & Build Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -s --scan -Pversion=${{ needs.tagging.outputs.version }}
      - name: Setup git config
        run: |
          echo "Setting up Git user information"
          git config --global user.name "${{github.actor}}"
          git config --global user.email "<>"
      - name: Sanity check
        run: |
          echo "This is a prerelease: ${{ needs.tagging.outputs.prerelease }}"
      - name: Publish candidate
        if: ${{ needs.tagging.outputs.prerelease == 'true' }}
        run: ./gradlew candidate -Prelease.version=${{ needs.tagging.outputs.version }} -s --info
      - name: Publish release
        if: ${{ needs.tagging.outputs.prerelease == 'false' }}
        run: ./gradlew final -Prelease.version=${{ needs.tagging.outputs.version }} -s --info
      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kody-clientsdk-java.jar
          path: |
            **/build/libs/kody-clientsdk-java-*.jar            
            !**/build/libs/kody-clientsdk-java*-sources.jar

  release:
    needs:
      - tagging
      - publish
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "${{ needs.tagging.outputs.tag }}"
          tag: "${{ needs.tagging.outputs.tag }}"
          omitBody: true
          draft: false
          prerelease: ${{ needs.tagging.outputs.prerelease == 'true' }}
          makeLatest: ${{ needs.tagging.outputs.prerelease == 'false' }}
          artifacts: ${{ needs.publish.outputs.artifact }}
